# List of packages to be included/installed in ISO
# If these have dependencies, they will be pulled in automatically
#
acpid
gdb
influxdb
python2-influxdb
python2-gunicorn
iperf3
isomd5sum
python2-aodhclient
python2-oslo-log
python2-six
python-d2to1
hiera
python2-pecan
python-configobj
python-pep8
python2-rsa
ruby-shadow
swig
syslinux
iotop
linuxptp
procps-ng
python-daemon
python-pyudev
curl
lvm2
time
postgresql
postgresql-server
postgresql-contrib
targetcli
strace
wget
bind-utils
selinux-policy
pm-utils
tcpdump
sysstat
smartmontools
collectd
puppet-collectd
socat
attr

# for realtime kernel
rtctl
rt-setup

# For low-latency compute
OVMF

# neutron bgp
python2-pankoclient

# ima plugin for RPM
ntfs-3g
ntfsprogs
python-memcached
python2-coverage

# kubernetes packages
docker-ce
etcd
docker-forward-journald

# Add debugging tools
zip
unzip
traceroute

# support for persistent sessions
screen

