#!/bin/bash

# This program is a wrapper around build-pkgs-parallel and build-pkgs-serial

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

usage () {
    echo ""
    echo "Usage: "
    echo "   Create source and binary rpms:"
    echo "   build-pkgs [--serial] [args]"
}

SERIAL_FLAG=0

for arg in "$@"; do
    case "$1" in
        --serial) SERIAL_FLAG=1 ;;
    esac
done

which mock_tmpfs_umount >> /dev/null
if [ $? -ne 0 ]; then
    SERIAL_FLAG=1
fi

if [ $SERIAL_FLAG -eq 1 ]; then
    echo "build-pkgs-serial $@"
    build-pkgs-serial "$@"
else
    echo "build-pkgs-parallel $@"
    build-pkgs-parallel "$@"
fi

