#!/bin/bash

# This program is a wrapper around build-srpms-parallel and build-srpms-serial

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

usage () {
    echo ""
    echo "Usage: "
    echo "   Create source rpms:"
    echo "   build-srpms [--serial] [args]"
}

SERIAL_FLAG=0

for arg in "$@"; do
    case "$1" in
        --serial) SERIAL_FLAG=1 ;;
    esac
done

which mock_tmpfs_umount >> /dev/null
if [ $? -ne 0 ]; then
    SERIAL_FLAG=1
fi

if [ $SERIAL_FLAG -eq 1 ]; then
    echo "build-srpms-serial $@"
    build-srpms-serial "$@"
else
    echo "build-srpms-parallel $@"
    build-srpms-parallel "$@"
fi

